Web/Controllers/ResellerController.cs
using AutoMapper;
using HubManPractices.Models;
using HubManPractices.Service;
using HubManPractices.Service.ViewModels;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Data.Entity.Infrastructure;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI;
using Util;
using WebApp.Filters;
using System.Web.Caching;
namespace WebApp.Controllers
{
    public class ResellerController : Controller
    {
        private readonly IRoleService RoleService;
        private readonly IResellerService ResellerService;
        private readonly IClientService ClientService;
        private readonly ISubscriptionsService SubService;

        public ResellerController(IResellerService resellerservice,IRoleService Rs,IClientService Cs,ISubscriptionsService Ss)
        {
            this.ResellerService = resellerservice;
            this.RoleService = Rs;
            this.ClientService = Cs;
            this.SubService= Ss;
        }
        // GET: Reseller
        [MyAuthFilter(Roles= "Global Admin , Reseller Admin")]
        public ActionResult Index()
        { 
            IEnumerable<ResellerViewModel> ResellerViewModels;
                if (User.IsInRole("Global Admin"))
                {
                    ResellerViewModels = ResellerService.MapToViewModel(ResellerService.GetResellers());

                    return View(ResellerViewModels);
                }
                else
                {
                    try
                    {
                        ResellerViewModels = ResellerService.MapToViewModel(ResellerService.GetUserReseller(User.Identity.GetUserId()));
                        TempData["ResellerID"] = ResellerViewModels.FirstOrDefault().ResellerID;
                        TempData["ActiveClass"] = "welcomeTag";
                        return RedirectToAction("ResellerIndex",new { ResellerID=ResellerViewModels.FirstOrDefault().ResellerID});
                    }
                    catch(NullReferenceException ex)
                    {
                        TempData["NoReseller"] = "This admin has no reseller";
                        return RedirectToAction("Index", "Home");
                    }
                }
            
        }
        public ActionResult ResellerIndex(Guid ResellerID)
        {
            IEnumerable<ClientViewModel> clientViewModels = ClientService.MapToViewModel(ResellerService.GetResellerClients(ResellerID));
            IEnumerable<ClientViewModel> Recent10Clients = ClientService.MapToViewModel(ResellerService.GetRecent10Clients(ResellerService.GetResellerClients(ResellerID)));
            Dictionary<string, int> chartData = ResellerService.GetChartData(ResellerID);
            IEnumerable<OfficeSubscriptionViewModel> Subs = SubService.MapToViewModel(SubService.GetAllSubscriptions());
            ResellerIndexViewModel myModel = new ResellerIndexViewModel() { ChartData = chartData, RecentClients = Recent10Clients, Clients = clientViewModels, AllSubs = Subs };
            return View(myModel);
        }
        [MyAuthFilter(Roles = "Global Admin")]
        public ActionResult Create()
        {
            if (HasPermission("Add Reseller"))
                return View();
            return View("~/Views/Home/UnAuthorized.cshtml");
        }
        [HttpPost]
        [MyAuthFilter(Roles = "Global Admin")]
        public ActionResult Create(FormCollection Fc)
        {
            if (HasPermission("Add Reseller"))
            {
                try
                {
                    Reseller reseller = new Reseller() { Name = Fc["Name"], ClientsQuota = Int32.Parse(Fc["ClientsQuota"]) };
                    reseller.ResellerID = Guid.NewGuid();
                    ResellerService.CreateReseller(reseller);
                    if(EmailCorrectFormat(Fc["ResellerMail"]))
                    {
                        ResellerService.AddResellerUser(reseller, Fc["ResellerMail"]);
                    }
                    
                    if (Request.Files.Count > 0)
                    {
                        var file = Request.Files[0];

                        if (file != null && file.ContentLength > 0)
                        {
                            var fileName = reseller.Name + ".PNG";
                            var path = Path.Combine(Server.MapPath("~/Content/Images/"), fileName);
                            file.SaveAs(path);
                        }
                    }
                }
                catch (DbUpdateException ex)
                {
                    TempData["Exists"] = "Reseller already exists";
                    return RedirectToAction("Create");
                }
                catch (Exception ex)
                {
                    TempData["Error Adding Reseller"] = "Error while creating the Reseller";
                    return RedirectToAction("Create");
                }

                TempData["CreateSuccess"] = "Client created successfully";
                return RedirectToAction("Index");
            }
            return View("~/Views/Home/UnAuthorized.cshtml");
        }

        private bool EmailCorrectFormat(string mail)
        {
            if (mail.Contains(".com") && mail.Contains("@"))
                return true;
            else return false;
        }

        [MyAuthFilter(Roles = "Global Admin, Reseller Admin")]
        public ActionResult Edit(Guid ResellerID)
        {
            if(HasPermission("Edit Reseller"))
            {
                Reseller ToBeEdited=ResellerService.GetById(ResellerID);
                return View(ResellerService.MapToViewModel(ToBeEdited));
            }
            return View("~/Views/Home/UnAuthorized.cshtml");
        }

        [MyAuthFilter(Roles = "Global Admin, Reseller Admin")]
        [HttpPost]
        public ActionResult Edit(Reseller reseller)
        {
            if (HasPermission("Edit Reseller"))
            {
                try
                {
                    ResellerService.EditReseller(reseller);
                }
                catch (DbUpdateException ex)
                {
                    TempData["EditFail"] = "Reseller already exists";
                    return RedirectToAction("Edit", new { id = reseller.ResellerID });
                }
                catch(Exception ex)
                {
                    TempData["EditError"] = "Error in Editing the Reseller";
                    return RedirectToAction("Edit", new { id = reseller.ResellerID });
                }
                TempData["EditSuccess"] = "Edit successful";
                return RedirectToAction("Index");
            }
            return View("~/Views/Home/UnAuthorized.cshtml");
        }

        [MyAuthFilter(Roles= "Global Admin")]
        [HttpPost]
        public ActionResult Delete(Guid ResellerID)
        {
            if(HasPermission("Delete Reseller"))
            {
                
                Reseller ToBeDeleted =ResellerService.GetById(ResellerID);
                try
                {
                    ResellerService.DeleteReseller(ToBeDeleted);
                    return RedirectToAction("Index");
                }
                catch(Exception ex)
                {
                    TempData["DeleteError"]="Error in Deleting the Reseller";
                    return RedirectToAction("Index");
                }
                
            }
            return View("~/Views/Home/UnAuthorized.cshtml");
        }

        public ActionResult Search(string Query)
        {
            return View("Index", ResellerService.MapToViewModel(ResellerService.SearchForResellers(Query)));
        }

        public bool HasPermission(string PName)
        {
            if (RoleService.HasPermission(User.Identity.GetUserId(), PName) == null)
                return false;
            return true;
        }
        public string  GetImageUrl(string UserID)
        {
            if(User.IsInRole("Global Admin"))
            {
                return "";
            }
            if (System.Web.HttpContext.Current.Cache[UserID] == null)
            {
                System.Web.HttpContext.Current.Cache.Insert(UserID, ResellerService.GetUserReseller(UserID).FirstOrDefault().ResellerImage.ToString(), null, Cache.NoAbsoluteExpiration, Cache.NoSlidingExpiration);
            }

            return System.Web.HttpContext.Current.Cache[UserID].ToString();
        }
        public Guid GetResellerID(string UserID)
        {
            Reseller reseller = ResellerService.GetUserReseller(UserID).FirstOrDefault();
            return reseller.ResellerID;
        }
    }
}

Web/Views/Reseller/Create.cshtml
@model HubManPractices.Service.ViewModels.ResellerViewModel

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@if (TempData["Exists"]!=null)
{
    <div class="alert alert-danger">@TempData["Exists"]</div>
}

@if (TempData["Error Adding Reseller"] != null)
{
    <div class="alert alert-danger">@TempData["Error Adding Reseller"]</div>
}



<div class="contactContainer">
    <div class="banner">
        <div>Create</div>
    </div>
    @using (Html.BeginForm("Create", "Reseller", FormMethod.Post,new { enctype = "multipart/form-data", id="contactItem"}))
    {
        @Html.AntiForgeryToken()
        <label for="Name">@Html.DisplayNameFor(model => model.Name)</label>
        @Html.EditorFor(model => model.Name, new { htmlAttributes = new { placeholder = "Enter Full Name" } })
        <label for="ClientsQuota">@Html.DisplayNameFor(model => model.ClientsQuota)</label>
        @Html.EditorFor(model => model.ClientsQuota, new { htmlAttributes = new { placeholder = "Enter Clients Quota" } })
        <label for="ResellerMail">Reseller Mail</label>
       <input type="text" id="ResellerMail" name="ResellerMail" placeholder="Enter Your Reseller Mail" />
        <input type='file' name="file" id="imgInp" />
        <img id="blah" src="#" alt="your image" />
        <input type="submit" value="Create" />
    }
</div>



@section scripts
{
    <script type="text/javascript" src="@Url.Content("/Scripts/script.js")"></script>

}

Web/Views/Reseller/Edit.cshtml
@model HubManPractices.Service.ViewModels.ResellerViewModel

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@if (TempData["EditFail"]!=null)
{
    <div class="alert alert-danger">@TempData["Edit Fail"]</div>
}

@if (TempData["EditError"] != null)
{
    <div class="alert alert-danger">@TempData["EditError"]</div>
}
<head>
    <title>Edit Reseller</title>
    <link href="~/Content/style.css" rel="stylesheet" type="text/css" />
</head>



<div class="contactContainer">
    <div class="banner">
        <div>Edit</div>
    </div>
    @using (Html.BeginForm("Edit", "Reseller", FormMethod.Post, new {@id="contactItem"}))
    {
        @Html.AntiForgeryToken()
        @Html.Hidden("ResellerID", Model.ResellerID)
        <label for="Name">@Html.DisplayNameFor(model=>model.Name)</label>
        @Html.EditorFor(model => model.Name, new { htmlAttributes = new { placeholder = "Enter Full Name" } })
        if(User.IsInRole("Global Admin"))
        {
             <label for="ClientsQuota">@Html.DisplayNameFor(model => model.ClientsQuota)</label>
            @Html.EditorFor(model => model.ClientsQuota, new { htmlAttributes = new { placeholder = "Enter Clients Quota" } })
        
        }
        <input type="submit" value="Save" />
    }
</div>


    
    
    
    
    
    <!--
         <div class="form-horizontal">
        <h4>ResellerViewModel</h4>
        <hr />
        @@Html.ValidationSummary(true)
        <div class="form-group">
            @@Html.Hidden("ResellerID",Model.ResellerID)
        </div>

        <div class="form-group">
            @@Html.LabelFor(model => model.Name, new { @@class = "control-label col-md-2" })
            <div class="col-md-10">
                @@Html.EditorFor(model => model.Name)
                @@Html.ValidationMessageFor(model => model.Name)
            </div>
        </div>

        <div class="form-group">
            @@*if (User.IsInRole("Global Admin"))
               {
                     @@Html.LabelFor(model => model.ClientsQuota, new { @@class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @@Html.EditorFor(model => model.ClientsQuota)
                        @@Html.ValidationMessageFor(model => model.ClientsQuota)
                    </div>
               }
               else
                 {
                     @@Html.Hidden("ClientsQuota",Model.ClientsQuota)
                 }*@@
              
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>


    -->
   

Web/Views/Reseller/Index.cshtml
@model IEnumerable<HubManPractices.Service.ViewModels.ResellerViewModel>

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<head>
    <title>Index</title>
</head>


@if (TempData["EditSuccess"] != null)
{
    <div class="alert alert-success">@TempData</div>
}



@if (TempData["CreateSuccess"] != null)
{
    <div class="alert alert-success">@TempData["CreateSuccess"]</div>
}

@if (TempData["DeleteError"] != null)
{
    <div class="alert alert-danger">@TempData["DeleteError"]</div>
}



@if (User.IsInRole("Global Admin"))
{
    using (Html.BeginForm("Search", "Reseller", FormMethod.Get, new { @style = "float:left;margin-bottom:15px" }))
    {
        @Html.TextBox("Query", null, new { @placeholder = "Reseller Name.." })
        <button type="submit" value="" class="btn btn-default btn-sm"><span class="glyphicon glyphicon-search"></span></button>
    }
}



<div class="contactContainer">
    <div class="banner">
        <div>Resellers</div>
        @if(User.IsInRole("Reseller Admin"))
        {
            <img src="@Url.Content(Model.FirstOrDefault().ResellerImage)"/>
        }
        <div class="showClients">
            @if (Html.Action("HasPermission", "Reseller", new { pname = "Add Reseller" }).ToString() == "True")
            {
                @Html.ActionLink("Add Reseller", "Create")
            }
        </div>
    </div>
    <div class="clearfix"></div>

    <div class="clientRow">
        <div class="clientHeader">
            <div class="clientRowHeader">
                @Html.DisplayNameFor(model => model.FirstOrDefault().Name)
            </div>
            <div class="clientRowHeader">
                @Html.DisplayNameFor(model => model.FirstOrDefault().ClientsQuota)
            </div>
            <div class="clientRowHeader">
                Action
            </div>
        </div>

        @foreach (var item in Model)
        {
            <div class="clientRowBody">
                <div class="clientRowBodyContainer">@item.Name</div>
                <div class="clientRowBodyContainer">@item.ClientsQuota</div>
                <div class="action">
                    <a href="/Reseller/Edit?ResellerID=@item.ResellerID" data-type="edit">Edit</a>
                    <a href="/Client/Index?ResellerID=@item.ResellerID" data-type="clients">Clients</a>
                    @if (Html.Action("HasPermission", "Reseller", new { pname = "Delete Reseller" }).ToString() == "True")
                    {
                        using (Html.BeginForm("Delete", "Reseller", FormMethod.Post, new { @style = "display:inline-block" }))
                        {
                            @Html.Hidden("ResellerID", item.ResellerID)
                            <input type="submit" value="Delete" data-type="Delete" />
                        }
                    }
                </div>
            </div>
        }
    </div>

</div>

Web/Views/Reseller/ResellerIndex.cshtml
@model HubManPractices.Service.ViewModels.ResellerIndexViewModel
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link href="~/Content/font-awesome.min.css" rel="stylesheet" />
    <link href="~/Content/font-awesome.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/Content/owl.carousel.min.css">
    <link rel="stylesheet" href="~/Content/owl.theme.default.css">
</head>


<body>
    @{
        int TotalEmployees = 0;
        foreach (var client in Model.Clients)
        {
            TotalEmployees += client.Seats;
        }
    }
    <div id="welcome">
        <div class="welcomeOverview">
            <div class="welcomeBody">
                <div class="welcomeName">Clients Overview</div>
                <div class="welcomeDetails">
                    <div class="welcomeItem">
                        <i class="fa fa-briefcase" aria-hidden="true"></i>
                        <div id="clientNumber">@Model.Clients.Count()</div>
                        <div class="itemName">Clients</div>
                    </div>
                    <div class="welcomeItem">
                        <i class="fa fa-user" aria-hidden="true"></i>
                        <div id="empNumber">@TotalEmployees</div>
                        <div class="itemName">Employees</div>
                    </div>
                    <!--<div class="welcomeItem">
                         <i class="fa fa-database" aria-hidden="true"></i>
                         <div id="quotaNumber">62%</div>
                         <div class="itemName">Quota</div>
                    </div> -->
                </div>
            </div>
            <div class="viewClient">
                <img src="~/Content/Images/layout.png" alt="">
                <div><a href="@Url.Action("Index", "Client", new { ResellerID = Model.Clients.FirstOrDefault().ResellerID })">View/Edit Clients <i class="fa fa-arrow-circle-right"></i></a></div>
            </div>
            <div class="addClient" id="addClient">
                <img src="~/Content/Images/human.png" alt="">
                <div><a href="@Url.Action("Create", "Client", new { ResellerID = Model.Clients.FirstOrDefault().ResellerID })">Add New Client <i class="fa fa-arrow-circle-right"></i></a></div>
            </div>
        </div>
        <div class="welcomeStatistic">
            <div class="statisticBody">
                <div class="statisticName">Statistic</div>
            </div>
            <div class="statisticDetails">
                Monthly Installations
            </div>
            <div id="chart">
                <ul id="bars">
                    @foreach (var item in Model.ChartData)
                    {
                        <li><div data-percentage="@item.Value" class="bar"></div><span>@item.Key</span></li>
                    }
                </ul>
            </div>
        </div>
        <div class="recentClients">
            <div class="recentName">Your Recent Clients</div>
            <div class="viewAll"><a href="@Url.Action("Index", "Client", new { ResellerID = Model.Clients.FirstOrDefault().ResellerID })">View All  <i class="fa fa-arrow-circle-right"></i></a></div>
            <div id="recentContainer" class="owl-carousel">
                @foreach (var client in Model.RecentClients)
                {

                <div class="recentDetails ">
                    <div class="clientLeft">
                        <div><a href="">@client.ClientName</a></div>
                        <div class="clientLoc"><i class="fa fa-map-marker" aria-hidden="true"></i>@client.Location</div>
                        <div class="clientDate">Added: <span>@client.CreationDate.ToString("MM - dd - yy")</span></div>
                    </div>
                    <div class="clientRight">
                        <div class="clientEmp">
                            <p class="empNumber">@client.Seats</p>
                            <p class="empName">Employees</p>
                        </div>
                        @*<div class="clientLic">
                            <div>
                                <p class="empNumber">E3</p>
                                <p class="empName">Employees</p>
                            </div>
                        </div>*@
                    </div>
                </div>


                }
            </div>
        </div>
        <div class="overlay">
            <div class="popup">
                <div class="popupHeader">
                    <i class="fa fa-pencil" aria-hidden="true"></i>
                    <div id="popupTitle">Add / Edit</div>
                    <div class="popupExit" id="exitAddClient">
                        <i class="fa fa-times" aria-hidden="true"></i>
                    </div>
                </div>
                <div class="popupBody">
                    @using (Html.BeginForm("SendEmail", "Account", FormMethod.Post, new { @id = "contactItem" }))
                    {
                        @Html.AntiForgeryToken()

                        @Html.ValidationSummary(true)

                        @Html.Hidden("ResellerID", Model.Clients.FirstOrDefault().ResellerID)

                        <input id="ClientName" name="ClientName" type="text" placeholder="Enter Client Name" />
                        <input id="ContactName" name="ContactName" type="text" placeholder="Enter Contact Name" />
                        <input id="ContactTitle" name="ContactTitle" type="text" placeholder="Enter Contact Title" />
                        <input id="Location" name="Location" type="text" placeholder="Enter Your Location" />
                        <input id="ContactNumber" name="ContactNumber" type="number" placeholder="Enter Contact Number" />
                        if (TempData["NumberWrongFormat"] != null)
                        {
                            @Html.ValidationMessage("ContactNumber", TempData["NumberWrongFormat"])
                        }
                        <input id="ContactMail" name="ContactMail" type="text" placeholder="Enter Contact Mail" />
                        if (TempData["EmailWrongFormat"] != null)
                        {
                            @Html.ValidationMessage("ContactMail", TempData["EmailWrongFormat"])
                        }
                        <input id="Seats" name="Seats" type="number" placeholder="Enter Number Of Seats" />
                      
                            foreach (var Sub in Model.AllSubs)
                            {
                                @Html.Hidden(Sub.MonthlyFee.ToString(), Sub.SubscriptionID)
                                @Html.TextBox(Sub.SubscriptionName, null, new { @type = "number", @placeholder = "Enter Number of " + Sub.SubscriptionName + " you have.." })
                            }
                        <input type="submit" value="Add Client" />
                    }
                </div>
            </div>
        </div>
    </div>

    <script src="~/scripts/jquery-3.1.1.min.js"></script>
    <script src="~/scripts/script.js"></script>
    <script src="~/scripts/owl.carousel.min.js"></script>
</body>
</html>

<script>
    $(document).ready(function () {

        //document.getElementById('nav').style.backgroundImage="url(@@Model.Item1.FirstOrDefault().reseller.ResellerImage.Replace("~","").ToString()";
        var Keys = @Html.Raw(Json.Encode(Model.ChartData.Keys));
        var Values =@Html.Raw(Json.Encode(Model.ChartData.Values));
        var ctx = document.getElementById("myChart");
        var myChart = new Chart(ctx, {
            type: 'bar',
            data: {
                labels: Keys,
                datasets: [{
                    label: ' Number Of Clients',
                    data: Values,
                    backgroundColor: [
                        'rgba(255, 99, 132, 0.2)',
                        'rgba(54, 162, 235, 0.2)',
                        'rgba(255, 206, 86, 0.2)',
                        'rgba(75, 192, 192, 0.2)',
                        'rgba(153, 102, 255, 0.2)',
                        'rgba(255, 159, 64, 0.2)'
                    ],
                    borderColor: [
                        'rgba(255,99,132,1)',
                        'rgba(54, 162, 235, 1)',
                        'rgba(255, 206, 86, 1)',
                        'rgba(75, 192, 192, 1)',
                        'rgba(153, 102, 255, 1)',
                        'rgba(255, 159, 64, 1)'
                    ],
                    borderWidth: 1
                }]
            },
            options: {
                scales: {
                    yAxes: [{
                        ticks: {
                            beginAtZero: true,
                            stepSize: 1
                        }
                    }]
                }
            }
        });

    });
   
</script>



@section scripts
{
    <script type="text/javascript" src="@Url.Content("/Scripts/script.js")"></script>
}