Web/Controllers/ClientController.cs
using HubManPractices.Models;
using HubManPractices.Service;
using HubManPractices.Service.ViewModels;
using System;
using Microsoft.AspNet.Identity;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApp.Filters;
using System.Data.Entity.Infrastructure;
using PagedList;

namespace WebApp.Controllers
{
    public class ClientController : Controller
    {
        private readonly IClientService ClientService;
        private readonly IRoleService RoleService;
        private readonly IResellerService ResellerService;
        private readonly ISubscriptionsService SubscriptionService;
        private readonly IActionService ActionService;

        public ClientController(IActionService As, IClientService clientservice, IResellerService resellerservice, IRoleService Rs, ISubscriptionsService SS)
        {
            this.ActionService = As;
            this.ClientService = clientservice;
            this.ResellerService = resellerservice;
            this.RoleService = Rs;
            this.SubscriptionService = SS;
        }
        // GET: Client
        [MyAuthFilter(Roles = "Global Admin , Reseller Admin")]
        public ActionResult Index(Guid ResellerID, string sortOrder, int? page)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewBag.DateSortParm = sortOrder == "Date" ? "date_desc" : "Date";

            IEnumerable<Client> ResellerClients = ResellerService.GetResellerClients(ResellerID);
            foreach (var client in ResellerClients)
            {
                client.reseller = ResellerService.GetById(ResellerID);
                if (ClientService.NeedsRenewal(client))
                {
                    client.Status = "Waiting For Renewal";
                    ClientService.SaveClient();
                }
            }
            TempData["ResellerID"] = ResellerID;
            switch (sortOrder)
            {
                case "name_desc":
                    ResellerClients = ResellerClients.OrderByDescending(s => s.ClientName);
                    break;
                case "Date":
                    ResellerClients = ResellerClients.OrderBy(s => s.Expiry);
                    break;
                case "date_desc":
                    ResellerClients = ResellerClients.OrderByDescending(s => s.Expiry);
                    break;
                default:
                    ResellerClients = ResellerClients.OrderBy(s => s.ClientName);
                    break;
            }
            int pageSize = 2;
            int pageNumber = (page ?? 1);

            if (Request.IsAjaxRequest())
            {
                return (ActionResult)PartialView("ClientListPartial", ClientService.MapToViewModel(ResellerClients).ToPagedList(pageNumber, pageSize));
            }
            else
            {
                return View(ClientService.MapToViewModel(ResellerClients).ToPagedList(pageNumber, pageSize));
            }
        }
        [MyAuthFilter(Roles = "Global Admin,Reseller Admin")]
        public ActionResult Create(Guid ResellerID)
        {
            if (HasPermission("Add Client"))
            {
                if (ResellerService.QuotaFull(ResellerID))
                {
                    TempData["QuotaFull"] = "Your Clients Quota is full";
                    return RedirectToAction("Index", new { ResellerID = ResellerID });
                }
                else
                {
                    TempData["ResellerID"] = ResellerID;
                    Client client = new Client();
                    ClientViewModel c = ClientService.MapToViewModel(client);
                    IEnumerable<OfficeSubscriptionViewModel> Subscriptions = SubscriptionService.MapToViewModel(SubscriptionService.GetAllSubscriptions());
                    var myTuple = new Tuple<ClientViewModel, IEnumerable<OfficeSubscriptionViewModel>>(c, Subscriptions);
                    return View(myTuple);
                }
            }
            return View("~/Views/Home/UnAuthorized.cshtml");
        }

        [HttpPost]
        [MyAuthFilter(Roles = "Global Admin,Reseller Admin")]
        public ActionResult Reactivate(FormCollection Fc)
        {
            Client ToReactivate = ClientService.GetClientByNameAndMail(Fc["ClientName"], Fc["ContactMail"]);
            ToReactivate.IsDeleted = false;
            ToReactivate.Status = "On Hold";
            ToReactivate.Expiry = null;
            ToReactivate.IsExpiryNull = true;
            var i = 0;
            foreach (var Sub in ToReactivate.ClientSubscriptions)
            {
                ToReactivate.ClientSubscriptions.ElementAt(i).IsDeleted = false;
                i++;
            }
            try
            {
                ClientService.EditClient(ToReactivate);
            }
            catch (DbUpdateException ex)
            {
                TempData["ReActivateError"] = "Error in Readding the client again..";
                return RedirectToAction("Create", new { ResellerID = ToReactivate.ResellerID });
            }

            HubManPractices.Models.Action Reactivate = new HubManPractices.Models.Action() { ActionID = Guid.NewGuid(), ActionName = "ReAactivated", Client = ToReactivate, Date = DateTime.Now };
            ActionService.CreateAction(Reactivate);
            TempData["ReactivateClient"] = "The Client has been Reactivated";
            return RedirectToAction("Index", new { ResellerID = ToReactivate.ResellerID });
        }

        [HttpPost]
        [MyAuthFilter(Roles = "Global Admin,Reseller Admin")]
        public ActionResult ReAdd(FormCollection Fc)
        {
            Client ToReAdd = ClientService.GetClientByNameAndMail(Fc["ClientName"], Fc["ContactMail"]);
            IEnumerable<OfficeSubscription> Subscriptions = SubscriptionService.GetAllSubscriptions();

            foreach (var Sub in ToReAdd.ClientSubscriptions)
            {
                if (Fc[Sub.OfficeSubscription.MonthlyFee.ToString()] != "")
                {
                    Sub.IsDeleted = false;
                    Sub.UsersPerSubscription = Int32.Parse(Fc[Sub.OfficeSubscription.MonthlyFee.ToString()]);
                }
            }
            ToReAdd.ContactName = Fc["ContactName"];
            ToReAdd.ContactNumber = Int32.Parse(Fc["ContactNumber"]);
            ToReAdd.ContactTitle = Fc["ContactTitle"];
            ToReAdd.Seats = Int32.Parse(Fc["Seats"]);
            ToReAdd.Expiry = null;
            ToReAdd.IsDeleted = false;
            ToReAdd.IsExpiryNull = true;
            ToReAdd.Status = Fc["Status"];
            try
            {
                ClientService.EditClient(ToReAdd);
            }
            catch (DbUpdateException ex)
            {
                TempData["ReAddError"] = "Error in Readding the client again..";
                return RedirectToAction("Create", new { ResellerID = ToReAdd.ResellerID });
            }
            return RedirectToAction("Index", new { ResellerID = ToReAdd.ResellerID });
        }

        [MyAuthFilter(Roles = "Global Admin,Reseller Admin")]
        [HttpPost]
        public ActionResult Delete(Guid ClientID)
        {
            if (HasPermission("Delete Client"))
            {

                Client ToBeDeleted = ClientService.GetById(ClientID);
                try
                {
                    ClientService.DeleteClient(ToBeDeleted);
                    HubManPractices.Models.Action Terminate = new HubManPractices.Models.Action() { ActionID = Guid.NewGuid(), ActionName = "Terminated", Client = ToBeDeleted, Date = DateTime.Now };
                    ActionService.CreateAction(Terminate);
                    return RedirectToAction("Index", new { ResellerID = ToBeDeleted.ResellerID });
                }
                catch (Exception ex)
                {
                    TempData["DeleteError"] = "Error in Deleting the Client";
                    return RedirectToAction("Index", new { ResellerID = ToBeDeleted.ResellerID });
                }

            }
            return View("~/Views/Home/UnAuthorized.cshtml");
        }

        [MyAuthFilter(Roles = "Global Admin,Reseller Admin")]
        [HttpPost]
        public ActionResult Suspend(Guid ClientID)
        {
            if (HasPermission("Suspend Client"))
            {

                Client ToBeSuspended = ClientService.GetById(ClientID);
                try
                {
                    ToBeSuspended.Status = "Suspended";
                    ClientService.SaveClient();
                    HubManPractices.Models.Action Suspend = new HubManPractices.Models.Action() { ActionID = Guid.NewGuid(), ActionName = "Suspended", Client = ToBeSuspended, Date = DateTime.Now };
                    ActionService.CreateAction(Suspend);
                    return RedirectToAction("Index", new { ResellerID = ToBeSuspended.ResellerID });
                }
                catch (Exception ex)
                {
                    TempData["SuspendError"] = "Error in Suspending the Client";
                    return RedirectToAction("Index", new { ResellerID = ToBeSuspended.ResellerID });
                }

            }
            return View("~/Views/Home/UnAuthorized.cshtml");
        }

        [MyAuthFilter(Roles = "Global Admin,Reseller Admin")]
        [HttpPost]
        public ActionResult Activate(Guid ClientID)
        {
            if (HasPermission("Activate Client"))
            {

                Client ToBeActivated = ClientService.GetById(ClientID);
                try
                {
                    ToBeActivated.Status = "Activated";
                    ToBeActivated.Expiry = DateTime.Now.AddMonths(1).Date;
                    ToBeActivated.IsExpiryNull = false;
                    ClientService.SaveClient();

Web/Views/Shared/_Layout.cshtml
@using Microsoft.AspNet.Identity;
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    <script src="~/scripts/jquery.unobtrusive-ajax.js"></script>
    <link rel="stylesheet" href="~/Content/style.css" />
    @RenderSection("scripts", required: false)
    @RenderSection("Styles", false)

</head>
<body>
    
    @{
        string image;
        if (User.Identity.IsAuthenticated)
        {
            image = Html.Action("GetImageUrl", "Reseller", new { UserID = User.Identity.GetUserId() }).ToString();
        }
        else
        {
            image = "";
        }
    }
 
    <div class="nav" style="background-image:url(@image.Replace("~","").ToString()">
        <div class="toggleIcon">
            <a href="#" class="toggleAction"><i class="fa fa-bars" aria-hidden="true"></i></a>
            <a href="#" class="toggleAction"><i class="fa fa-times" aria-hidden="true"></i></a>
        </div>
        <div class="navLeft">
            <a href="#">
                <img src="/Content/Images/logo.png"alt="Itworx Hub"/>
            </a>
        </div>
        <div class="mobileNavContainer">
            <div class="mobileNavBg"></div>
            <div class="mobileNav">
                <ul class="mobileAction">
                    <li><a href="@Url.Action("ResellerIndex", "Reseller", new { ResellerID = Html.Action("GetResellerID", "Reseller", new { UserID = User.Identity.GetUserId() }) })"><i class="fa fa-th" aria-hidden="true"></i>Welcome</a></li>
                    <li><a href="@Url.Action("Index", "Client", new { ResellerID = Html.Action("GetResellerID", "Reseller", new { UserID = User.Identity.GetUserId() })})"><i class="fa fa-briefcase" aria-hidden="true"></i>Clients</a></li>
                    <li><a href="#"><i class="fa fa-pie-chart" aria-hidden="true"></i>Statistics</a></li>
                </ul>
                <hr />
                <ul class="profile">
                    <li><a href="#"><i class="fa fa-user" aria-hidden="true"></i>profile</a></li>
                    <li class="noIcon"><a href="javascript:document.getElementById('logoutForm').submit()">Signout</a></li>
                </ul>
                <hr />
                <ul class="privacy">
                    <li class="noIcon"><a href="#">Help</a></li>
                    <li class="noIcon"><a href="#">Contact Us</a></li>
                    <li class="noIcon"><a href="#">Privacy</a></li>
                </ul>
                @*<hr />
                <ul class="lan">
                    <li class="noIcon"><a href="#">عربي</a></li>
                </ul>*@
            </div>
        </div>
        <div class="navRight">
            <div class="brand-logo">
                <a href="#">
                    <img src="~/Content/Images/zain-logo.png" alt="zain logo"/>
                </a>
            </div>

            <div class="action">
                <ul>
                    <li><a id="welcomeTag" href="@Url.Action("ResellerIndex", "Reseller", new { ResellerID = Html.Action("GetResellerID", "Reseller", new { UserID = User.Identity.GetUserId() }) })"><i class="fa fa-th" aria-hidden="true"></i>Welcome</a></li>
                    <li><a id="clientsTag" href="@Url.Action("Index", "Client", new { ResellerID = Html.Action("GetResellerID", "Reseller", new { UserID = User.Identity.GetUserId() })})" ><i class="fa fa-briefcase" aria-hidden="true"></i>Clients</a></li>
                    <li><a href="#"><i class="fa fa-pie-chart" aria-hidden="true"></i>Statistics</a></li>
                </ul>
            </div>
            @Html.Partial("_LoginPartial")
        </div>
    </div>
  

    <div class="container body-content">
        @RenderBody()
    </div>
    <script>
        $(document).ready(function () {
            var pathname = window.location.pathname;
            if (pathname == "/Client/Index")
            {
                document.getElementById("clientsTag").className="active";
            }
            else
            {
                document.getElementById("welcomeTag").className = "active";
            }
        });
      
    </script>
    <script src="~/scripts/jquery-3.1.1.min.js"></script>
    <script src="~/scripts/script.js"></script>
    <footer>
        <div class="copyright">All copyrights are reserved for ITWORX hub 2016</div>
        <div class="policy">
            <ul>
                <li><a href="#">Help</a></li>
                <li><a href="#">Contact Us</a></li>
                <li><a href="#">Privacy</a></li>
            </ul>
        </div>
    </footer>
</body>
</html>